from pathlib import Path

base = Path(r'c:\Users\32328\Desktop\zhiXiShuXue')
student_js = base / 'backend' / 'routes' / 'student.js'
knowledge_vue = base / 'frontend' / 'src' / 'views' / 'student' / 'Knowledge.vue'

text = student_js.read_text(encoding='utf-8')

text = text.replace(
"function buildPracticeKnowledgePointChanges(practiceQuestions, questionResults, targetKnowledgePointId) {\n  const questionMap = {};\n  practiceQuestions.forEach(question => {\n    questionMap[question.id] = question;\n  });\n\n  const summary = {};\n  questionResults.forEach(result => {\n    const question = questionMap[result.questionId];\n    if (!question) return;\n\n    const kpIds = Array.isArray(question.knowledgePoints) ? question.knowledgePoints : [];\n    kpIds.forEach(kpId => {\n      if (targetKnowledgePointId && kpId !== targetKnowledgePointId) return;\n\n      if (!summary[kpId]) {\n        const kp = db.findById('knowledgePoints', kpId);\n        summary[kpId] = {\n          knowledgePointId: kpId,\n          knowledgePointName: kp ? kp.name : kpId,\n          questionCount: 0,\n          correctCount: 0,\n          wrongCount: 0\n        };\n      }\n\n      summary[kpId].questionCount += 1;\n      if (result.correct) {\n        summary[kpId].correctCount += 1;\n      } else {\n        summary[kpId].wrongCount += 1;\n      }\n    });\n  });\n\n  return Object.values(summary).map(item => {\n    const masteryAfter = item.questionCount > 0\n      ? Math.round(item.correctCount / item.questionCount * 100)\n      : 0;\n\n    return {\n      ...item,\n      masteryAfter,\n      statusLabel: masteryAfter >= 80 ? '已掌握' : (masteryAfter >= 60 ? '待巩固' : '薄弱'),\n      statusType: masteryAfter >= 80 ? 'success' : (masteryAfter >= 60 ? 'warning' : 'danger')\n    };\n  });\n}\n",
"function buildPracticeKnowledgePointChanges(studentId, practiceQuestions, questionResults, targetKnowledgePointId) {\n  const questionMap = {};\n  practiceQuestions.forEach(question => {\n    questionMap[question.id] = question;\n  });\n\n  const summary = {};\n  questionResults.forEach(result => {\n    const question = questionMap[result.questionId];\n    if (!question) return;\n\n    const kpIds = Array.isArray(question.knowledgePoints) ? question.knowledgePoints : [];\n    kpIds.forEach(kpId => {\n      if (targetKnowledgePointId && kpId !== targetKnowledgePointId) return;\n\n      if (!summary[kpId]) {\n        const kp = db.findById('knowledgePoints', kpId);\n        const profile = db.findOne('studentKnowledgeProfiles', { studentId, knowledgePointId: kpId });\n        summary[kpId] = {\n          knowledgePointId: kpId,\n          knowledgePointName: kp ? kp.name : kpId,\n          questionCount: 0,\n          correctCount: 0,\n          wrongCount: 0,\n          masteryBefore: profile ? Math.max(0, Math.min(100, parseInt(profile.masteryRate || 0, 10))) : 100\n        };\n      }\n\n      summary[kpId].questionCount += 1;\n      if (result.correct) {\n        summary[kpId].correctCount += 1;\n      } else {\n        summary[kpId].wrongCount += 1;\n      }\n    });\n  });\n\n  return Object.values(summary).map(item => {\n    const profile = db.findOne('studentKnowledgeProfiles', {\n      studentId,\n      knowledgePointId: item.knowledgePointId\n    });\n    const masteryAfter = profile\n      ? Math.max(0, Math.min(100, parseInt(profile.masteryRate || 0, 10)))\n      : item.masteryBefore;\n\n    return {\n      ...item,\n      masteryBefore: item.masteryBefore,\n      masteryAfter,\n      statusLabel: masteryAfter >= 80 ? '已掌握' : (masteryAfter >= 60 ? '待巩固' : '薄弱'),\n      statusType: masteryAfter >= 80 ? 'success' : (masteryAfter >= 60 ? 'warning' : 'danger')\n    };\n  });\n}\n")

text = text.replace(
"  const weakSummary = buildWeakPointSummary(studentId);\n  const matchedWeak = weakSummary.find(item => item.id === knowledgePointId);\n  const masteryRate = matchedWeak ? parseInt(matchedWeak.masteryRate || 0, 10) : 100;\n\n  const specificQuestions = buildKnowledgePointSpecificQuestions(knowledgePoint, masteryRate);\n",
"  const weakSummary = buildWeakPointSummary(studentId);\n  const matchedWeak = weakSummary.find(item => item.id === knowledgePointId);\n  const masteryRate = matchedWeak ? parseInt(matchedWeak.masteryRate || 0, 10) : 100;\n\n  if (matchedWeak && matchedWeak.isLeaf && masteryRate >= 80) {\n    return [];\n  }\n\n  const specificQuestions = buildKnowledgePointSpecificQuestions(knowledgePoint, masteryRate);\n")

text = text.replace(
"    let directMasteryRate = latestPracticeChange ? latestPracticeChange.masteryAfter : 100;\n",
"    let directMasteryRate = 100;\n    const profile = db.findOne('studentKnowledgeProfiles', {\n      studentId,\n      knowledgePointId: item.id\n    });\n\n    if (profile && Number(profile.attemptCount || 0) > 0) {\n      directMasteryRate = Math.max(0, Math.min(100, parseInt(profile.masteryRate || 0, 10)));\n    } else if (latestPracticeChange) {\n      directMasteryRate = Math.max(0, Math.min(100, parseInt(latestPracticeChange.masteryAfter || 0, 10)));\n    }\n")

text = text.replace(
"    const latestPractice = db.find('learningRecords')\n      .filter(record => {\n        return (\n          record.studentId === student.id &&\n          record.recordType === 'practice' &&\n          record.knowledgePointId === knowledgePointId\n        );\n      })\n      .sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt))[0] || null;\n\n    res.json({\n",
"    const latestPractice = db.find('learningRecords')\n      .filter(record => {\n        return (\n          record.studentId === student.id &&\n          record.recordType === 'practice' &&\n          record.knowledgePointId === knowledgePointId\n        );\n      })\n      .sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt))[0] || null;\n\n    const weakSummary = knowledgePointId && knowledgePointId !== 'custom'\n      ? buildWeakPointSummary(student.id)\n      : [];\n    const currentKnowledgePoint = weakSummary.find(item => item.id === knowledgePointId) || null;\n\n    if (!wrongQuestion && currentKnowledgePoint && currentKnowledgePoint.isLeaf && currentKnowledgePoint.masteryRate >= 80) {\n      questions = [];\n    }\n\n    res.json({\n")

text = text.replace(
"    const payload = calculateAnswerPayload(targetQuestionIds, answers || {});\n    const practiceQuestions = targetQuestionIds\n      .map(id => {\n        const question = db.findById('questions', id);\n        if (question) return question;\n        return {\n          id,\n          knowledgePoints: [deriveKnowledgePointId({ id, content: '', knowledgePoints: [] }, knowledgePointId)],\n          content: '',\n          type: 'fill'\n        };\n      })\n      .filter(Boolean);\n\n    const knowledgePointChanges = buildPracticeKnowledgePointChanges(\n      practiceQuestions,\n      payload.questionResults,\n      knowledgePointId === 'custom' ? null : knowledgePointId\n    );\n\n    const practiceRecord = createLearningRecord({\n",
"    const payload = calculateAnswerPayload(targetQuestionIds, answers || {});\n    const practiceQuestions = targetQuestionIds\n      .map(id => {\n        const question = db.findById('questions', id);\n        if (question) return question;\n        return {\n          id,\n          knowledgePoints: [deriveKnowledgePointId({ id, content: '', knowledgePoints: [] }, knowledgePointId)],\n          content: '',\n          type: 'fill'\n        };\n      })\n      .filter(Boolean);\n\n    const knowledgePointChangesBefore = buildPracticeKnowledgePointChanges(\n      student.id,\n      practiceQuestions,\n      payload.questionResults,\n      knowledgePointId === 'custom' ? null : knowledgePointId\n    );\n\n    recordQuestionResults(student.id, payload.questionResults, {\n      answeredAt: new Date().toISOString(),\n      source: 'practice-submit'\n    });\n\n    const knowledgePointChanges = buildPracticeKnowledgePointChanges(\n      student.id,\n      practiceQuestions,\n      payload.questionResults,\n      knowledgePointId === 'custom' ? null : knowledgePointId\n    ).map(item => {\n      const beforeItem = knowledgePointChangesBefore.find(change => change.knowledgePointId === item.knowledgePointId);\n      return {\n        ...item,\n        masteryBefore: beforeItem ? beforeItem.masteryBefore : item.masteryBefore\n      };\n    });\n\n    const practiceRecord = createLearningRecord({\n")

student_js.write_text(text, encoding='utf-8')

text = knowledge_vue.read_text(encoding='utf-8')
text = text.replace(
"          <el-empty v-else description=\"当前知识点暂无可用练习题\" />\n",
"          <el-empty\n            v-else\n            :description=\"getPracticeEmptyText()\"\n          />\n")
text = text.replace(
"function loadSelectedPracticeQuestions() {\n  if (!selectedKnowledge.value.id) {\n    selectedPracticeQuestions.value = []\n    practiceAnswers.value = {}\n    practiceFeedbackMap.value = {}\n    return Promise.resolve()\n  }\n\n  return api.get('/student/practice/' + selectedKnowledge.value.id)\n",
"function loadSelectedPracticeQuestions() {\n  if (!selectedKnowledge.value.id) {\n    selectedPracticeQuestions.value = []\n    practiceAnswers.value = {}\n    practiceFeedbackMap.value = {}\n    return Promise.resolve()\n  }\n\n  if (getMasteryStatus(selectedKnowledge.value.masteryRate) === 'mastered' && selectedKnowledge.value.isLeaf) {\n    selectedPracticeQuestions.value = []\n    practiceAnswers.value = {}\n    practiceFeedbackMap.value = {}\n    return Promise.resolve()\n  }\n\n  return api.get('/student/practice/' + selectedKnowledge.value.id)\n")
text = text.replace(
"function getDifficultyLabel(level) {\n  if (level === 'easy') return '简单'\n  if (level === 'medium') return '中等'\n  if (level === 'hard') return '困难'\n  return level || '未知'\n}\n\nfunction submitSelectedPractice() {\n",
"function getDifficultyLabel(level) {\n  if (level === 'easy') return '简单'\n  if (level === 'medium') return '中等'\n  if (level === 'hard') return '困难'\n  return level || '未知'\n}\n\nfunction getPracticeEmptyText() {\n  if (!selectedKnowledge.value.id) return '请先选择一个知识点'\n  if (getMasteryStatus(selectedKnowledge.value.masteryRate) === 'mastered' && selectedKnowledge.value.isLeaf) {\n    return '当前知识点已掌握，暂不生成个性化练习题'\n  }\n  return '当前知识点暂无可用练习题'\n}\n\nfunction submitSelectedPractice() {\n")
knowledge_vue.write_text(text, encoding='utf-8')
